### PR TITLE
A getter herlper function to check if the yaml data are parsed and se…

### LINKED ISSUE #175: Parser breaks when a setting is missing from the .config
The Parser breaks when a setting or option is missing from the config.

It would be very helpful if the exception would output which setting was missing or being accessed when it broke. This would help the user fix the problem.

### PR DESCRIPTION
**Pull request by UCLGuichard**
Fixes #175 
The paths to the config file and to the folder to write the output are now passed as arguments.

### CODE REVIEW

File: cpp/purify/yaml-parser.cc [hunk 1]
```diff
@@ -15,6 +15,8 @@
 #include <yaml-cpp/yaml.h>
 #include "yaml-parser.h"
 #include <assert.h>
+#include <unistd.h>
```
Comment (Luke-Pratley) [inline cpp/purify/yaml-parser.cc]: remove?

File: cpp/purify/yaml-parser.cc [hunk 2]
```diff
@@ -28,10 +30,44 @@ YamlParser::YamlParser (const std::string& filepath)
...
+      YAML::Node config = YAML::LoadFile(this->filepath_);
+      // A bit of defensive programming
+      assert(config.Type() == YAML::NodeType::Map);
+      this->config_file = config;
+    }
+  catch(YAML::BadFile& exception)
+    {
+      char cwd[1024];
+      getcwd(cwd, sizeof(cwd));
+      std::cerr << "The input file path " << this->filepath_ << " could not be found from " << cwd << std::endl;
```
Comment (Luke-Pratley) [inline cpp/purify/yaml-parser.cc]: rather than using std::cerr put this in the runtime_error

File: cpp/purify/yaml-parser.cc [hunk 3]
```diff
@@ -28,10 +30,44 @@ YamlParser::YamlParser (const std::string& filepath)
...
+    {
+      faulty_variable = std::string(index);	  
+      node = node[index];
+      if (!node.IsDefined())
+	{
+	  throw std::runtime_error("The initialisation of " + faulty_variable + " is wrong.");
+	}
+    }
+  try
+    {
```
Comment (Luke-Pratley) [inline cpp/purify/yaml-parser.cc]: Check if node.size() > 1.

Comment (Luke-Pratley) [reply cpp/purify/yaml-parser.cc]: If `node.size > 1`, then iterate through the container and push back the elements into the container `T<typename T:: value_type>`.

File: cpp/tests/parser_test.cc [hunk 4]
```diff
@@ -9,7 +9,7 @@
 
 TEST_CASE("Yaml parser and setting variables test")
 {
-  std::string file_path = "../data/config/config.yaml";
+  std::string file_path = "../../../data/config/config.yaml";
```
Comment (Luke-Pratley) [inline cpp/tests/parser_test.cc]: use the function `purify::notinstalled::data_filename("config/config.yaml");` You will need to include `#include "purify/directories.h"`

File: cpp/purify/yaml-parser.cc (hunk 2 above)
Comment (Luke-Pratley) [reply cpp/purify/yaml-parser.cc]: Also, why are you using a raw array of type `char`? Why not a std::string?

File: cpp/purify/yaml-parser.cc (hunk 1 above)
Comment (UCLGuichard) [reply cpp/purify/yaml-parser.cc]: Actually no story. Needed for the `getcwd` function

Comment (Luke-Pratley) [reply cpp/purify/yaml-parser.cc]: Okay, that explains some other things. We should probably use boost for this, since it is a bit nicer. Look at https://theboostcpplibraries.com/boost.filesystem-files-and-directories

File: cpp/tests/parser_test.cc (hunk 4 above)
Comment (UCLGuichard) [reply cpp/tests/parser_test.cc]: what does it do ? Does it return a path ?

File: cpp/purify/yaml-parser.cc (hunk 2 above)
Comment (UCLGuichard) [reply cpp/purify/yaml-parser.cc]: That's what `getcwd` takes as argument.

File: cpp/tests/parser_test.cc (hunk 4 above)
Comment (UCLGuichard) [reply cpp/tests/parser_test.cc]: done

File: cpp/purify/yaml-parser.cc (hunk 3 above)
Comment (UCLGuichard) [reply cpp/purify/yaml-parser.cc]: done
